### ISSUE TITLE
Details about fine-tuning the language model

### ISSUE THREAD

**Issue by shadowkiller33** [OSU-NLP-Group/SELM#1]
Hi, thanks for your wonderful work, so impressed!

I got a little question about SELM: when you're fine-tuning the LM (step5-6 in page 3) until perfectly reproduing the message given the prompt, the model is in the state
$\theta^{D} =\theta_{0} + \theta_{d}$ 
or 
$\theta^{D} =\theta_{0} + P \cdot \theta_{d}$?
I'm a little confused. Can't be more appreciated for your reply, thanks.

**Comment by shadowkiller33** [comment]
Also, when you sample a subset of model parameters as trainable parameters, is the sample process also determined by the random seed $k$?

**Comment by samuelstevens** [comment]
> $\theta^D = \theta^D_0 + P \cdot \theta^d$

This is correct. $P$ projects $\theta^d$ from dimension of $d$ to dimension of $D$ (where $D > d$). We only change the values in $\theta^d$ and keep $P$ and $\theta^D_0$ frozen.

> Also, when you sample a subset of model parameters as trainable parameters, is the sample process also determined by the random seed $k$?

We actually "update" all parameters of the original model because the low-dimensional vector $\theta^d$ is randomly projected into $\mathbb{R}^D$. So the first element of the vector $P \cdot \theta^d \in \mathbb{R}^D$ is a linear combination of all elements in $\theta^d$. The second element is a different linear combination of all elements in $\theta^d$. We're not actually sampling a subset of the model parameters to train. 

$k$ determines $P$.

Does that help?

**Comment by shadowkiller33** [comment]
Got it, thanks a lot!
